---
openapi: 3.0.2
info:
  title: freight-types-integrationV1
  version: 1.0.0
  description: |
    API de integração de tipos de frete (Freight-Types) V1

    Compatível com a versão V11 do serviço de negócio Sales
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Freight-Types
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Freight-Types-Integration_V1_FullResponse'
          description: Returns a list of Freight-Types
        401:
          description: Unauthorized
      summary: Listar tipos de frete
      description: Retorna uma lista de tipos de frete cadastradas ou determinadas
        formas com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Freight-Types-Integration_V1_BodyCreate'
      tags:
        - Freight-Types
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            default: minimum
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            oneOf:
              - $ref: '#/components/schemas/Freight-Types-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Freight-Types-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Freight-Types-Integration_V1_BodyUpsert'
            discriminator:
              mapping:
                create: '#/components/schemas/Freight-Types-Integration_V1_BodyCreate'
                update: '#/components/schemas/Freight-Types-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Freight-Types-Integration_V1_BodyUpsert'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                schema:
                  $ref: '#/components/schemas/Freight-Types-Integration_V1_FullResponse'
          description: Returns a freight type register
        401:
          description: Unauthorized
      summary: Criar e atualizar tipos de frete
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: sales'
        schema:
          default: sales
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: freight-types-integration'
        schema:
          default: freight-types-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Freight-Types-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Freight-Types-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Freight-Types-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: C
        description:
          type: string
          example: CIF
        code:
          type: string
          example: C
        acronym:
          type: string
          example: C
        active:
          type: boolean
          example: true
        defaultRecord:
          type: boolean
          example: false
      example:
        externalId: C
        description: CIF
        code: C
        acronym: C
        active: true
        defaultRecord: false
    Freight-Types-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: C
        description:
          type: string
          example: CIF
        code:
          type: string
          example: C
        acronym:
          type: string
          example: C
        active:
          type: boolean
          example: true
        defaultRecord:
          type: boolean
          example: false
      example:
        externalId: C
        description: CIF
        code: C
        acronym: C
        active: true
        defaultRecord: false
    Freight-Types-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
          example: C
        description:
          type: string
          example: CIF
        code:
          type: string
          example: C
        acronym:
          type: string
          example: C
        active:
          type: boolean
          example: true
        defaultRecord:
          type: boolean
          example: false
      example:
        id: 0d61f837-0cad-3d41-af80-b84d143e1257
        createdAt: 2020-08-20T22:02:37.906Z
        updatedAt: 2020-08-20T22:02:37.906Z
        externalId: C
        description: CIF
        code: C
        acronym: C
        active: true
        defaultRecord: false
    Freight-Types-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
          example: C
        description:
          type: string
          example: CIF
        code:
          type: string
          example: C
        acronym:
          type: string
          example: C
        active:
          type: boolean
          example: true
        defaultRecord:
          type: boolean
          example: false
      example:
        id: 0d61f837-0cad-3d41-af80-b84d143e1257
        createdAt: 2020-08-20T22:02:37.906Z
        updatedAt: 2020-08-20T22:02:37.906Z
        externalId: C
        description: CIF
        code: C
        acronym: C
        active: true
        defaultRecord: false
    Freight-Types-Integration_V1_BodyCreate:
      required:
        - externalId
        - active
        - defaultRecord
        - description
        - code
      type: object
      properties:
        externalId:
          description: Código único para o registro no sistema externo para referência
          type: string
          example: C
        description:
          description: Descrição do tipo de frete
          type: string
          example: CIF
        code:
          description: Código do tipo de frete
          type: string
          example: C
        acronym:
          description: Sigla do tipo de frete
          type: string
          example: C
        active:
          description: Indica se o tipo de frete está ativo para uso
          type: boolean
          example: true
        defaultRecord:
          description: Indica se o registro de tipo de frete é padrão
          type: boolean
          example: false
      example:
        externalId: C
        description: CIF
        code: C
        acronym: C
        active: true
        defaultRecord: false
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
