openapi: 3.0.2
info:
  title: pipeline-stages-integrationV1
  version: 1.0.0
  description: |
    API de integração de estágios da pipeline (Pipeline-Stages) V1

    Compatível com a versão V6 do serviço de negócio Opportunity
  contact: {}
servers:
- url: https://{url}/api/{version}/integration
  description: Integration Router Server
  variables:
    url:
      default: app2.mastercrm.ws
      description: URL de acesso ao Integration-Router
    version:
      default: v1
      description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
      - Pipeline-Stages
      parameters:
      - name: Integration-Filter
        description: |
          Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
          RestQuery.


          Se o header for omitido, lista todos os registros

          Se o header não contiver valores, lista todos os registros
        schema:
          type: string
        in: header
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_FullResponse'
          description: Returns a list of pipeline-stages
        401:
          description: Unauthorized
      summary: Listar Pipeline-Stages
      description: Retorna uma lista de estágios da pipeline cadastradas ou determinadas
        estapa com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyCreate'
      tags:
      - Pipeline-Stages
      parameters:
      - name: Integration-Filter
        description: |
          Filtro do registro específico para a ação. Deve-se usar o identificador principal da
          entidade (ID).
        schema:
          type: string
        in: header
        required: false
      - name: Integration-Response
        description: |
          Nível de detalhe do retorno da API. São suportados atualmente:

          **full** - Resposta completa, equivalente a um GET no recurso

          **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
          registro

          Se o header não for informado, por padrão o retorno será equivalente ao nível
          **minimum**
        schema:
          default: minimum
          enum:
          - full
          - minimum
          type: string
        in: header
        required: false
      - name: Integration-Action
        description: |
          Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
          body da requisição.
        schema:
          oneOf:
          - $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyCreate'
          - $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyUpdate'
          - $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyUpsert'
          - $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyDelete'
          discriminator:
            mapping:
              create: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyCreate'
              update: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyUpdate'
              upsert: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyUpsert'
              delete: '#/components/schemas/Pipeline-Stages-Integration_V1_BodyDelete'
        in: header
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline-Stages-Integration_V1_FullResponse'
                discriminator:
                  mapping:
                    full: '#/components/schemas/Pipeline-Stages-Integration_V1_FullResponse'
                    minimum: '#/components/schemas/Pipeline-Stages-Integration_V1_MinimumResponse'
          description: Returns a pipeline stage register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar Pipeline-Stages
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do registro especificado no header **Integration-Filter**
    parameters:
    - name: Integration-Service
      description: 'Serviço responsável pela entidade. Exemplo: opportunity'
      schema:
        default: opportunity
        type: string
      in: header
      required: true
    - name: Integration-Resource
      description: 'Recurso para requisição. Exemplo: pipeline-stages-integration'
      schema:
        default: pipeline-stages-integration
        type: string
      in: header
      required: true
    - name: Integration-Version
      description: 'Versão da API de integração. Exemplo: v1'
      schema:
        default: v1
        type: string
      in: header
      required: true
components:
  schemas:
    Pipeline-Stages-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Pipeline-Stages-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Pipeline-Stages-Integration_V1_BodyDelete:
      description: No body
      type: object
    Pipeline-Stages-Integration_V1_BodyUpdate:
      properties:
        stageId:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        externalId:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        pipelineId:
          format: uuid
          type: string
          example: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        rank:
          type: number
          example: 1
      example:
        pipelineId: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        externalId: Stage1#Pipe1
        rank: 1
        stageId: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
    Pipeline-Stages-Integration_V1_BodyUpsert:
      properties:
        stageId:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        externalId:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        pipelineId:
          format: uuid
          type: string
          example: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        rank:
          type: number
          example: 1
      example:
        pipelineId: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        externalId: Stage1#Pipe1
        rank: 1
        stageId: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
    Pipeline-Stages-Integration_V1_FullResponse:
      properties:
        id:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        stageId:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        externalId:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        pipelineId:
          format: uuid
          type: string
          example: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        rank:
          type: number
          example: 1
      example:
        id: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        createdAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        pipelineId: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        externalId: Stage1#Pipe1
        rank: 1
        stageId: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
    Pipeline-Stages-Integration_V1_GetResponse:
      properties:
        id:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        stageId:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        externalId:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        pipelineId:
          format: uuid
          type: string
          example: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        rank:
          type: number
          example: 1
      example:
        id: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        createdAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        pipelineId: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        externalId: Stage1#Pipe1
        rank: 1
        stageId: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
    Pipeline-Stages-Integration_V1_BodyCreate:
      required:
      - externalId
      - pipelineId
      - stageId
      - rank
      type: object
      properties:
        stageId:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        externalId:
          format: uuid
          type: string
          example: 2bb960bf-e789-4aba-8916-8d53e84b6c4f
        pipelineId:
          format: uuid
          type: string
          example: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        rank:
          type: number
          example: 1
      example:
        pipelineId: b36196de-dbe9-4dd7-a419-5c0ca65395a4
        externalId: Stage1#Pipe1
        rank: 1
        stageId: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
tags:
- name: APP2
  description: Ambiente APP2
- name: integration
  description: ""
